name: vassalize
version: 1.1.0
summary: send and read messages as a discord bot user
description: |
  **this is not a selfbot. thats against the discord tos and i want to keep using discord**

grade: stable
confinement: strict

parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
  electron-app:
    after:
      - gnome
      - desktop-gnome-platform
    plugin: nodejs
    source: src/
    node-engine: 12.16.0
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libappindicator1
      - libsecret-1-0
      - libgtk-3-0
      - libdb5.3
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cd release-builds/*/
      mv * $SNAPCRAFT_PART_INSTALL/app
    stage:
      - -src/node_modules/*
      - -src/assets/*
      - -src/fonts/*
      - -src/*
      - -usr/share/doc/*
      - -usr/share/man/*
      - -share/man/*
      - -share/doc/*
      - -CHANGELOG.md
      - -README.md

apps:
  vassalize:
    command: bin/desktop-launch $SNAP/app/vassalize
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - unity7
      - wayland
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl